# Generated by Django 6.0.1 on 2026-05-02 10:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_sensor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('estado_operativo', models.BooleanField(default=True)),
                ('altitud_msnm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25830)),
            ],
            options={
                'db_table': 'estaciones_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='RedCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('material_construccion', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_caudal', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('longitud_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ultimo_mantenimiento', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=25830)),
            ],
            options={
                'db_table': 'red_canales',
            },
        ),
        migrations.CreateModel(
            name='ZonaConservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=150)),
                ('categoria_proteccion', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('area_hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_declaracion', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25830)),
            ],
            options={
                'db_table': 'zonas_conservacion',
            },
        ),
    ]
